ALTER TABLE camareiro ADD COLUMN codigo BIGINT;
ALTER TABLE camareiro ADD COLUMN empresa BIGINT;

ALTER TABLE categoria ADD COLUMN codigo BIGINT;
ALTER TABLE categoria ADD COLUMN empresa BIGINT;

ALTER TABLE cliente  ADD COLUMN codigo BIGINT;
ALTER TABLE cliente ADD COLUMN empresa BIGINT;

ALTER TABLE comanda ADD COLUMN codigo BIGINT;
ALTER TABLE comanda ADD COLUMN empresa BIGINT;

ALTER TABLE grupo ADD COLUMN codigo BIGINT;
ALTER TABLE grupo ADD COLUMN empresa BIGINT;

ALTER TABLE mesa ADD COLUMN codigo BIGINT;
ALTER TABLE mesa ADD COLUMN empresa BIGINT;

ALTER TABLE produto ADD COLUMN codigo BIGINT;
ALTER TABLE produto ADD COLUMN empresa BIGINT;